// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "odelolatojumi@gmail.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Gets message stats for the service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Get service metrics",
                "responses": {
                    "200": {
                        "description": "Service metrics",
                        "schema": {
                            "$ref": "#/definitions/models.ConsumerMetrics"
                        }
                    }
                }
            }
        },
        "/notification": {
            "post": {
                "description": "Sends a push notification with input payload to RabbitMQ queue",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notifications"
                ],
                "summary": "Sends Notification to web user",
                "parameters": [
                    {
                        "description": "Notification request payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.NotifPushRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "status: queued, request_id: string",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "error: validation failed or invalid notification type",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "error: internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.ConsumerMetrics": {
            "type": "object",
            "properties": {
                "messages_failed": {
                    "type": "integer"
                },
                "messages_processed": {
                    "type": "integer"
                },
                "messages_retried": {
                    "type": "integer"
                },
                "messages_succeeded": {
                    "type": "integer"
                }
            }
        },
        "models.NotifPushRequest": {
            "type": "object"
        },
        "models.NotificationType": {
            "type": "string",
            "enum": [
                "email",
                "push"
            ],
            "x-enum-varnames": [
                "Email",
                "Push"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Push Email MicroService",
	Description:      "A microservice that pushes notification to the designated web user",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
